name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Only run on merged PRs or direct pushes to main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "===== Starting deployment ====="
            
            # Check if the directory exists
            if [ -d "/home/e-do.studio-2.0" ]; then
              echo "Directory exists, navigating to /home/e-do.studio-2.0"
              cd /home/e-do.studio-2.0
            else
              echo "Directory does not exist, navigating to the correct location"
              cd /home/studio
            fi
            
            echo "Current directory: $(pwd)"
            
            # Check if git is initialized
            if [ ! -d .git ]; then
              echo "Initializing git repository"
              git init
              git remote add origin https://github.com/E-Do-Studio/e-do.studio-2.0.git
            else
              echo "Git already initialized"
              git remote -v
            fi
            
            # Ensure git knows who we are
            git config --global user.email "deploy@example.com"
            git config --global user.name "Deployment Bot"
            
            # Pull latest changes
            echo "Fetching latest changes from GitHub"
            git fetch --all
            git reset --hard origin/main
            
            # Install pnpm if not available
            if ! command -v pnpm &> /dev/null; then
              echo "Installing pnpm"
              npm install -g pnpm
            else
              echo "pnpm already installed: $(pnpm --version)"
            fi
            
            # Install dependencies and build
            echo "Installing dependencies"
            export PATH=$PATH:/root/.local/share/pnpm
            export PATH=$PATH:/root/.npm-global/bin
            pnpm install
            
            echo "Building application"
            pnpm build
            
            # Restart PM2 process
            echo "Checking PM2 processes"
            pm2 list
            
            echo "Restarting e-do-studio process"
            pm2 restart e-do-studio
            
            echo "===== Deployment complete ====="
