name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Only run on merged PRs or direct pushes to main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          timeout: 60m # Increase timeout to 60 minutes
          script: |
            echo "===== Starting zero-downtime deployment ====="
            
            # Set up directories
            MAIN_DIR="/home/e-do.studio-2.0"
            TEMP_DIR="/home/e-do.studio-2.0-temp"
            
            # Ensure main directory exists
            if [ ! -d "$MAIN_DIR" ]; then
              echo "Creating main directory and initializing repository"
              mkdir -p "$MAIN_DIR"
              cd "$MAIN_DIR"
              git init
              git remote add origin https://github.com/E-Do-Studio/e-do.studio-2.0.git
              git fetch origin main
              git checkout -b main origin/main
            else
              echo "Main directory exists, updating the repository"
              cd "$MAIN_DIR"
              # Clean and reset to handle any local changes
              git reset --hard HEAD
              git clean -f -d
              git pull origin main
            fi
            
            # Check Node.js version and update if needed
            echo "Checking Node.js version..."
            NODE_VERSION=$(node -v)
            echo "Current Node.js version: $NODE_VERSION"
            
            # Extract version number without 'v' prefix and split by dots
            VERSION_NUMBER=${NODE_VERSION#v}
            MAJOR_VERSION=$(echo $VERSION_NUMBER | cut -d. -f1)
            
            # Next.js 15+ requires Node.js 18.17.0 or higher
            if [ "$MAJOR_VERSION" -lt 18 ]; then
              echo "Node.js version is below 18, updating to Node.js 18 LTS..."
              
              # Install NVM if not already installed
              if [ ! -d "$HOME/.nvm" ]; then
                echo "Installing NVM..."
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
              fi
              
              # Load NVM
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              
              # Install and use Node.js 18 LTS
              nvm install 18
              nvm use 18
              
              echo "Node.js updated to: $(node -v)"
            fi
            
            # Create .env.local file with environment variables
            echo "Creating .env.local file with environment variables"
            cat > "$MAIN_DIR/.env.local" << EOL
            # API Keys
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            
            # Add any other environment variables your app needs
            NEXT_PUBLIC_SITE_URL=https://e-do.studio
            EOL
            
            # Clean cache directories to avoid errors
            echo "Cleaning cache directories..."
            rm -rf "$MAIN_DIR/.next/cache"
            rm -rf "$MAIN_DIR/node_modules/.cache"
            
            # Install dependencies
            echo "Installing dependencies with npm..."
            cd "$MAIN_DIR"
            npm install --no-fund --no-audit --prefer-offline
            
            # Build with optimized settings
            echo "Building application with production settings..."
            cd "$MAIN_DIR"
            NODE_OPTIONS="--max-old-space-size=4096 --no-deprecation" npm run build
            
            # If build succeeds, restart or start with PM2
            if [ $? -eq 0 ]; then
              echo "Build successful, updating PM2 service..."
              
              # Restart or start with PM2
              if pm2 list | grep -q "e-do-studio"; then
                echo "Restarting existing PM2 process..."
                pm2 restart e-do-studio
              else
                echo "Starting new PM2 process..."
                pm2 start npm --name "e-do-studio" -- start
              fi
              
              echo "Deployment complete!"
            else
              echo "Build failed, not updating PM2 service"
              exit 1
            fi
