name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Only run on merged PRs or direct pushes to main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          timeout: 60m # Increase timeout to 60 minutes
          script: |
            echo "===== Starting zero-downtime deployment ====="
            
            # Set up directories
            MAIN_DIR="/home/e-do.studio-2.0"
            TEMP_DIR="/home/e-do.studio-2.0-build"
            BACKUP_DIR="/home/e-do.studio-2.0-backup"
            
            # Completely remove and recreate temp directory
            echo "Preparing temporary build directory"
            rm -rf "$TEMP_DIR"
            mkdir -p "$TEMP_DIR"
            
            # Clone repository directly into the temp directory
            echo "Cloning repository into temporary directory"
            git clone --depth=1 https://github.com/E-Do-Studio/e-do.studio-2.0.git "$TEMP_DIR"
            cd "$TEMP_DIR"
            
            # Verify the clone was successful by checking for package.json
            if [ ! -f "$TEMP_DIR/package.json" ]; then
              echo "Error: package.json not found. Repository may not have been cloned correctly."
              exit 1
            fi
            
            # Check Node.js version and update if needed
            echo "Checking Node.js version..."
            NODE_VERSION=$(node -v)
            echo "Current Node.js version: $NODE_VERSION"
            
            # Extract version number without 'v' prefix and split by dots
            VERSION_NUMBER=${NODE_VERSION#v}
            MAJOR_VERSION=$(echo $VERSION_NUMBER | cut -d. -f1)
            
            # Next.js 15+ requires Node.js 18.17.0 or higher
            if [ "$MAJOR_VERSION" -lt 18 ]; then
              echo "Node.js version is below 18, updating to Node.js 18 LTS..."
              
              # Install NVM if not already installed
              if [ ! -d "$HOME/.nvm" ]; then
                echo "Installing NVM..."
                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
              fi
              
              # Load NVM
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              
              # Install and use Node.js 18 LTS
              nvm install 18
              nvm use 18
              
              echo "Node.js updated to: $(node -v)"
            fi
            
            # Create .env.local file with environment variables
            echo "Creating .env.local file with environment variables"
            cat > "$TEMP_DIR/.env.local" << EOL
            # API Keys
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            
            # Add any other environment variables your app needs
            NEXT_PUBLIC_SITE_URL=https://e-do.studio
            EOL
            
            # List directory contents to verify files are present
            echo "Verifying repository contents:"
            ls -la "$TEMP_DIR"
            
            # Install dependencies in temp directory
            echo "Installing dependencies with npm..."
            cd "$TEMP_DIR"
            npm install --no-fund --no-audit --prefer-offline
            
            # Build with optimized settings in temp directory
            echo "Building application with production settings..."
            cd "$TEMP_DIR"
            NODE_OPTIONS="--max-old-space-size=4096 --no-deprecation" npm run build
            
            # If build succeeds, proceed with the swap
            if [ $? -eq 0 ]; then
              echo "Build successful, preparing to swap directories..."
              
              # Keep backup of current version
              echo "Backing up current version"
              if [ -d "$BACKUP_DIR" ]; then
                rm -rf "$BACKUP_DIR"
              fi
              
              # Only backup if main directory exists
              if [ -d "$MAIN_DIR" ]; then
                mv "$MAIN_DIR" "$BACKUP_DIR"
              fi
              
              # Move new build to main directory
              echo "Moving new build to main directory"
              mv "$TEMP_DIR" "$MAIN_DIR"
              
              # Update PM2 configuration
              echo "Updating PM2 configuration"
              cd "$MAIN_DIR"
              
              # Restart or start with PM2
              if pm2 list | grep -q "e-do-studio"; then
                echo "Restarting existing PM2 process..."
                pm2 restart e-do-studio
              else
                echo "Starting new PM2 process..."
                pm2 start npm --name "e-do-studio" -- start
              fi
              
              echo "Zero-downtime deployment complete!"
            else
              echo "Build failed, not deploying new version"
              exit 1
            fi
