name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Only run on merged PRs or direct pushes to main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "===== Starting deployment ====="
            
            # Check if the directory exists
            if [ -d "/home/e-do.studio-2.0" ]; then
              echo "Directory exists, navigating to /home/e-do.studio-2.0"
              cd /home/e-do.studio-2.0
            else
              echo "Directory does not exist, navigating to the correct location"
              cd /home/studio
            fi
            
            echo "Current directory: $(pwd)"
            
            # Fix Git repository issues
            echo "Fixing Git repository"
            if [ -d ".git" ]; then
              # Fix locked refs by removing them
              rm -rf .git/refs/remotes/origin
              rm -f .git/index.lock
              
              # Re-initialize Git configuration
              git config --global user.email "deploy@example.com"
              git config --global user.name "Deployment Bot"
              
              # Re-add origin if needed
              if ! git remote | grep -q origin; then
                git remote add origin https://github.com/E-Do-Studio/e-do.studio-2.0.git
              fi
              
              # Clean and hard reset
              git fetch origin
              git reset --hard origin/main
            else
              # Initialize new repository
              git init
              git remote add origin https://github.com/E-Do-Studio/e-do.studio-2.0.git
              git fetch
              git checkout main || git checkout -b main origin/main
            fi
            
            # Use npm instead of pnpm to avoid compatibility issues
            echo "Installing dependencies with npm"
            npm install
            
            echo "Building application with npm"
            npm run build
            
            # Gestion du processus PM2 nommé e-do.studio
            echo "Vérification du processus PM2 e-do.studio"
            if pm2 list | grep -q "e-do.studio"; then
              echo "Le processus e-do.studio existe déjà, redémarrage..."
              pm2 restart e-do.studio
            else
              echo "Création du processus e-do.studio..."
              # Démarrer depuis le répertoire actuel
              pm2 start npm --name "e-do.studio" -- start
            fi
            
            echo "===== Deployment complete ====="
            echo "ATTENTION: PM2 restart NON EFFECTUÉ - À faire manuellement"
